### ISSUE TITLE
Reset bot after canceling setup

### ISSUE THREAD

**Issue by Howzet** [greatman/legendarybot#20]
Hello,

I've recently added the bot to my server and appear to have broken it in the process. I started doing the setup and on the first step where you choose what prefix to use, I typed something in response to someone and didn't mean for it to be the prefix the bot uses. I then canceled the setup and now it doesn't respond to any commands. What can I do?

Thanks.

**Comment by greatman** [comment]
You can @ the bot to do any commands. So if you do ``@Legendarybot setup`` you will start the setup

**Comment by Howzet** [comment]
The one thing I forgot to try. Thank you. :)
