### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by nightangelxx** [greatman/legendarybot#21]
Hello! I really liked your bot. I would like to add the translation to some commands. Is there such an opportunity? You can even use a separate command, for example !affixru. In my guild some people have a bad English.

P.S. sry for my bad En =))

**Comment by greatman** [comment]
Translation of the bot is planned, once I define a proper way to do it in my code (It won't be a !affixru command by example), I will allow everybody to participate in translating the bot.

**Comment by greatman** [comment]
Started the project here: https://crowdin.com/project/legendarybot

The code is starting to support it but no way to change the language yet.

**Comment by greatman** [comment]
Supported since https://github.com/greatman/legendarybot/commit/29515b3b035fe04764f98a41a8759f8ca8d27fcf . Use the !setlanguage to set the bot language.
