### ISSUE TITLE
Is the a way to reset legendary bot.

### ISSUE THREAD

**Issue by mejiggery** [greatman/legendarybot#39]
all was working fine and someone i share the discord channel with tried changing the response command for the bot. Now we cant get it to respond at all. tried kicking the bot from the server and re-inviting but still no response, so i can only assume discord or the bot is remembering the server and using the settings from before it was kicked... and yes i have made sure it still has all rights to channel. any help i would be grateful as the guild loved having the bot working.

**Comment by danbopes** [comment]
Tag the bot with:

> @LegendaryBot setup

**Comment by mejiggery** [comment]
Thankyou very much for your help @danbopes
